[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.virtualenv",
  "python311Packages.pymysql",
  "python311Packages.gunicorn",
  "mariadb"
]

[phases.install]
cmds = [
  # Crea y activa el entorno virtual en un solo paso
  "python -m venv /app/venv && source /app/venv/bin/activate",
  # Instala dependencias
  "/app/venv/bin/pip install --upgrade pip",
  "/app/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/app/venv/bin/gunicorn main_app.wsgi:application --bind 0.0.0.0:$PORT"