[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = [
  "cd BackEnd && python -m pip install --upgrade pip",
  "cd BackEnd && python -m pip install -r requirements.txt",
  "cd BackEnd && python -m pip show gunicorn",
  "cd BackEnd && python -m gunicorn --version || echo 'gunicorn not found!'",
  "which gunicorn || echo 'gunicorn no está en PATH'"
]

[phases.build]
cmds = [
  "cd BackEnd && python manage.py migrate",
  "cd BackEnd && python manage.py collectstatic --noinput"
]

[start]
cmd = "cd BackEnd && python -m gunicorn main_app.wsgi"
