[phases.setup]
nixPkgs = ["python311", "python311Packages.pymysql", "python311Packages.gunicorn", "mariadb"]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "gunicorn main_app.wsgi:application --bind 0.0.0.0:$PORT"
