[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.pymysql",
  "python311Packages.gunicorn"
]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade",
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt"  # Sin "cd BackEnd" porque ya estamos ahí
]

[start]
cmd = "gunicorn main_app.wsgi:application --bind 0.0.0.0:$PORT"  # Sin "cd BackEnd"