"""
Django settings for main_app project.
Generated by 'django-admin startproject' using Django 5.2.1.
"""

import os  # NEW: Asegúrate de que esta importación esté al inicio
import pymysql
pymysql.install_as_MySQLdb()

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# ===== CAMBIOS REQUERIDOS ===== #
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-9g&%6&xa14wy8llymd%040_gv90&vcjgq%+lxi*7s3v!e1(k1j')  # NEW: Usa variable de entorno
DEBUG = os.getenv('DEBUG', 'False') == 'True'  # NEW: Desactiva en producción
ALLOWED_HOSTS = ['*']  # NEW: Permite todos los hosts temporalmente (reemplaza con tu dominio luego)
CSRF_TRUSTED_ORIGINS = ['https://*.railway.app']  # NEW: Necesario para Railway
# ============================== #

# Application definition (todo lo que ya tenías se mantiene igual)
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # NEW: Para static files en producción
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main_app.urls'
TEMPLATES = [...]  # Mantén tu configuración actual
WSGI_APPLICATION = 'main_app.wsgi.application'

# Database (solo añade OPTIONS si usas SSL en Railway)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('MYSQLDATABASE', 'railway'),
        'USER': os.environ.get('MYSQLUSER', 'root'),
        'PASSWORD': os.environ.get('MYSQLPASSWORD', 'xKwcqZaQQxaFedxSdcWnKOXcrMgMlMLV'),
        'HOST': os.environ.get('MYSQLHOST', 'interchange.proxy.rlwy.net'),
        'PORT': os.environ.get('MYSQLPORT', '46707'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'ssl': {'ca': os.getenv('MYSQL_SSL_CA')} if os.getenv('MYSQL_SSL_CA') else {}  # NEW: Soporte para SSL
        }
    }
}

# Password validation (mantén tus validadores actuales)
AUTH_PASSWORD_VALIDATORS = [...]

# Internationalization (mantén tu configuración)
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (NEW: Configuración para producción)
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # NEW
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'  # NEW

# CORS (mantén tu configuración actual)
CORS_ALLOW_ALL_ORIGINS = True
CORS_ORIGIN_ALLOW_ALL = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'