# Generated by Django 5.2.1 on 2025-06-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('categoriaproducto', models.CharField(db_column='categoriaProducto', max_length=50)),
                ('cantidadstock', models.IntegerField(db_column='cantidadStock')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(blank=True, max_length=8, null=True)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('unidadmedida', models.CharField(db_column='unidadMedida', max_length=10)),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
            },
        ),
    ]
