# Generated by Django 5.2.1 on 2025-06-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idcarrito', models.AutoField(db_column='idCarrito', primary_key=True, serialize=False)),
                ('cantidadproductos', models.IntegerField(db_column='cantidadProductos')),
                ('preciototal', models.DecimalField(db_column='precioTotal', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'carrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('idcomprador', models.AutoField(db_column='idComprador', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'comprador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.AutoField(db_column='idPedido', primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=50)),
                ('fechapedido', models.DateTimeField(db_column='fechaPedido')),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('categoriaproducto', models.CharField(db_column='categoriaProducto', max_length=50)),
                ('cantidadstock', models.IntegerField(db_column='cantidadStock')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(blank=True, max_length=8, null=True)),
                ('fotos', models.CharField(max_length=255)),
                ('unidadmedida', models.CharField(db_column='unidadMedida', max_length=10)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('tipousuario', models.CharField(db_column='tipoUsuario', max_length=9)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('cedula', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('idvendedor', models.AutoField(db_column='idVendedor', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vendedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedorproducto',
            fields=[
                ('idvendedorproducto', models.AutoField(db_column='idVendedorProducto', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vendedorProducto',
                'managed': False,
            },
        ),
    ]
